environment:
  version: 20170620
  affix: esketch

platform:
- Win32
- x64

configuration: Release

os :
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017

test_script:
- esketch --version

# matrix:
  # allow_failures:
  # - os: Visual Studio 2017
  
after_build:
- echo | set /p="%affix%-v%version%" >>tmpfile.tmp || true
- echo | set /p="-win-" >>tmpfile.tmp || true
- echo | set /p="%platform%" >>tmpfile.tmp || true
- set /p target= <tmpfile.tmp
- echo .%target%.
- set dir=win32-%platform%
- mkdir %dir%
- copy %affix%.exe %dir%
- 7z a -ttar -so dummy %dir% | 7z a -si %target%.tar.gz

artifacts:
- path: '*.tar.gz'

deploy:
  tag: v$(version)
  description: ''
  provider: GitHub
  auth_token:
    secure: kKebvPLjikQbZ7E1Vm8omoYc9K0wOcKxjWsglp3+D4fV9ev/FaWr8ZBI+AseOTis
  draft: false
  prerelease: false
  on:
   os: "Visual Studio 2017"


