platform: Win32

configuration: Release

os : Visual Studio 2015

environment:
  version: 20170513.1
  affix: esketch
  dir: $(affix)-$(version)
  
before_deploy:
- mkdir %dir% || exit 1
- cp %affix%.exe %affix%.xcfg %affix%.xlcl %dir% || exit 1
- 7z a %dir%.zip %dir%

artifacts:
- path: $(dir).zip
  
deploy:
  tag: $(version)
  description: ''
  provider: GitHub
  auth_token:
    secure: kKebvPLjikQbZ7E1Vm8omoYc9K0wOcKxjWsglp3+D4fV9ev/FaWr8ZBI+AseOTis
  artifact: $(dir).zip
  draft: false
  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only


