platform: Win32

configuration: Release

os : Visual Studio 2015

artifacts:
- path: Release/esketch.exe
  
deploy:
  tag: 0.0.0
  release: esketch-v$(appveyor_build_version)
  description: 'Test'
  provider: GitHub
  auth_token:
    secure: kKebvPLjikQbZ7E1Vm8omoYc9K0wOcKxjWsglp3+D4fV9ev/FaWr8ZBI+AseOTis
  artifact: Release/esketch.exe
  draft: false
  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    appveyor_repo_tag: true        # deploy on tag push only


