os: linux
dist: trusty
compiler: g++

language: cpp

env:
  - ARCH=arm
  
sudo: required

script:
- "bash -ex .travis-ci.sh"

# To disable building on tags. Tags are supposed to begin with 'v' and only containing digits.
branches:
  except:
    - /^v[0-9]/
